[Main]
UserToken = ''                      # Токен пользователя, можно получить здесь: https://vkhost.github.io/
CommunityToken = ''                 # Токен сообщества, доступен для создания администраторам
CommunityAPIRateLimit = 5           # Ограничение запросов от ключа сообщества в секунду. (макс. значение = 20)
UserAPIRateLimit = 1                # Ограничение запросов от ключа пользователя в секунду. (макс. значение = 3)
StorageKeepAlive = 900              # Время хранения отложенных постов во внутреннем хранилище, в секундах;
                                    # по истечении - обновляет список отложенных постов

[Zerolog]
ConsoleLoggingEnabled = true
EncodeLogsAsJson = false
FileLoggingEnabled = true
Directory = "logs"
Filename = "otlozhka-bot.log"
MaxSize = 5
MaxBackups = 5
MaxAge = 30

[MessageBuilder]
MessageFormat = "📅 : %s\n📝: %s"  # Формат сообщения с информацией об отложенном посте
TimeFormat = '02.01.2006 15:04:05'  # Формат времени в сообщении
Timezone = 'Europe/Moscow'          # Часовой пояс

[MessageHandler]
OtlozhkaRegex = 'отложк[ауе]'       # Регулярное выражение для ключевых слов, триггерящих поиск отложки
UpdateStorageRegex = 'обнови'       # Регулярное выражение для ключевых слов, триггерящих обновление хранилища постов
PrintStorageRegex = 'календарь'
StorageUpdatedMsgs = ['Хранилище синхронизировано. Следующее обновление через 15 минут.']
StorageUpdatedCommendMsgs = ['Хранилище синхронизировано. Спасибо за Ваш труд!']
StorageEmptyMsgs = ['В хранилище пусто. Вероятно, в сообществе нет отложенных постов.']
PostponedPostsFoundMsgs = ['']
NoPostponedPostsFoundMsgs = ['Отложенных постов не найдено.']
