[main]
ErrorDotenvFailed = "Ошибка загрузки .env файла"
StartLongPollMsg = "Запускаем Long Poll"

[newMessageHandler]
IncomingMessage = "Входящее сообщение[id%d]: %s"
PostponedKeywordRegex = "отложк[ауе]"
PostponedPostsFound = ["Нашёл отложку, попробую-попытаюсь объяснить:", "Отложке быть!", "Получите, распишитесь:"]
NoPostponedPostsFound = ["Отложки не найдено.", "Не нашёл твою отложку. Тренируйся и приходи завтра!", "отложки нема"]
ErrorPostponedPostMessageFailed = "Тут должна была быть информация об отложенном посте, но её своровали инопланетяне/сервера ВКонтакте, лол!"

[message]
MessagePostDate =  "📅 Дата и время публикации: "
MessagePostAudio = "🎵 "
MessagePostText =  "📝 Текст публикации: "
TimeFormat = "02.01.2006 15:04:05 МСК"
Timezone = "Europe/Moscow"
ErrorLoadingTimeZone = "Ошибка загрузки часового пояса"
